export const template = {
    messages: [
      {
        id: 1,
        authorIsUser: false,
        isBookmarked: false,
        type: "chatMessage",
        body: "Reden wir über die Schule!",
        translation: "Let's talk about school!",
        words: [
            { id: "w1", de: "Reden wir", en: ["Let's talk"] },
            { id: "w2", de: "über", en: ["about"] },
            { id: "w2", de: "die Schule", en: ["school"] }
        ],
      },
      {
        id: 2,
        authorIsUser: false,
        isBookmarked: false,
        type: "chatMessage",
        body: "Ich studiere an einer Universität in Frankfurt.",
        translation: "I study in a university in Frankfurt.",
        words: [
          { id: "w2", de: "Ich", en: ["I"] },
          { id: "w3", de: "studiere", en: ["study"] },
          { id: "w4", de: "an einer Universität", en: ["in a university"] },
          { id: "w4", de: "in", en: ["in"] },
          { id: "w4", de: "Frankfurt", en: ["Frankfurt"] },
        ],
      },
      {
        id: 3,
        authorIsUser: true,
        isBookmarked: false,
        type: "chatMessage",
        body: "Hallo!",
        translation: "Hello!",
        words: [{ id: "w1", de: "hallo", en: ["hello"] }],
      },
      {
        id: 4,
        authorIsUser: false,
        isBookmarked: false,
        type: "chatMessage",
        body: "Hi!",
        translation: "Hi!",
        words: [
          { id: "w5", de: "Hi", en: ["Hi", "Hello", "Hey"] }
        ],
      },
      {
        id: 5,
        authorIsUser: true,
        isBookmarked: false,
        type: "chatMessage",
        body: "Ich studiere auch an einer Universität.",
        translation: "I also study in a university.",
        words: [
            { id: "w2", de: "Ich", en: ["I"] },
            { id: "w3", de: "studiere", en: ["study"] },
            { id: "w2", de: "auch", en: ["also"] },
            { id: "w4", de: "an einer Universität", en: ["in a university"] },
            { id: "w4", de: "in", en: ["in"] },
            { id: "w4", de: "Frankfurt", en: ["Frankfurt"] },
        ],
      },
      {
        id: 6,
        authorIsUser: false,
        isBookmarked: false,
        type: "chatMessage",
        body: "Echt? Wo?",
        translation: "Really? Where?",
        words: [
          { id: "w10", de: "Echt?", en: ["Really?"] },
          { id: "w11", de: "Wo?", en: ["Where?"] },
        ],
      },
      {
        id: 7,
        authorIsUser: true,
        isBookmarked: false,
        type: "chatMessage",
        body: "An der Universität Darmstadt",
        translation: "At the university Darmstadt.",
        words: [
          { id: "w15", de: "An", en: ["At"] },
          { id: "w16", de: "die Universität", en: ["university"] },
          { id: "w17", de: "Darmstadt", en: ["Darmstadt", "a city in central germany"] },
        ],
      },
      {
        id: 8,
        authorIsUser: false,
        isBookmarked: false,
        type: "chatMessage",
        body: "Echt? Meine Schwester studiert dort auch.",
        translation: "Really? My sister studies there too.",
        words: [
          { id: "w10", de: "Echt ?", en: ["Really ?"] },
          { id: "w18", de: "sister", en: ["die Schwester"] },
          { id: "w7", de: "studiert", en: ["studies"] },
          { id: "w19", de: "dort", en: ["there"] },
          { id: "w20", de: "auch", en: ["too", "also"] },
        ],
      },
      {
        id: 9,
        authorIsUser: false,
        isBookmarked: false,
        type: "chatMessage",
        body: "Ich muss gehen! Ich komme zu spät zum Bus.",
        translation: "Got to go! I am late for the bus.",
        words: [
          { id: "w21", de: "Ich", en: ["I"] },
          { id: "w22", de: "muss", en: ["must"] },
          { id: "w23", de: "gehen", en: ["go", "going", "walking"] },
          { id: "w24", de: "Ich komme zu spät", en: ["I am late"] },
          { id: "w24", de: "der Bus", en: ["bus"] },
        ],
      },
      {
        id: 10,
        authorIsUser: true,
        isBookmarked: false,
        type: "chatMessage",
        body: "Wiedersehen!",
        translation: "Bye!",
        words: [{ id: "w25", de: "wiedersehen", en: ["bye"] }],
      },
      {
        id: 11,
        type: "chatNotification",
        body: "You have already learned 25 words from this chat.",
      },
    ],
  };