export const template = {
  messages: [
    {
      id: 1,
      authorIsUser: false,
      isBookmarked: false,
      type: "chatMessage",
      body: "Laten we het over school hebben!",
      translation: "Let's talk about school!",
      words: [
          { id: "w1", nl: "Laten we", en: ["Let's"] },
          { id: "w2", nl: "over", en: ["about"] },
          { id: "w4", nl: "school", en: ["school"] }
      ],
    },
    {
      id: 2,
      authorIsUser: false,
      isBookmarked: false,
      type: "chatMessage",
      body: "Ik studeer aan een universiteit in Rotterdam.",
      translation: "I study in a university in Rotterdam.",
      words: [
        { id: "w1", nl: "Ich", en: ["I"] },
        { id: "w2", nl: "studeer", en: ["study"] },
        { id: "w3", nl: "in a university", en: ["in a university"] },
        { id: "w4", nl: "in", en: ["in"] },
      ],
    },
    {
      id: 3,
      authorIsUser: true,
      isBookmarked: false,
      type: "chatMessage",
      body: "Hallo!",
      translation: "Hello!",
      words: [{ id: "w1", nl: "hallo", en: ["hello"] }],
    },
    {
      id: 4,
      authorIsUser: false,
      isBookmarked: false,
      type: "chatMessage",
      body: "Hoi!",
      translation: "Hi!",
      words: [
        { id: "w5", nl: "Hoi", en: ["Hi", "Hello", "Hey"] }
      ],
    },
    {
      id: 5,
      authorIsUser: true,
      isBookmarked: false,
      type: "chatMessage",
      body: "Ik ook.",
      translation: "Me too.",
      words: [
          { id: "w1", nl: "Ik", en: ["I"] },
          { id: "w2", nl: "ook", en: ["too", "also"] },
      ],
    },
    {
      id: 6,
      authorIsUser: false,
      isBookmarked: false,
      type: "chatMessage",
      body: "Werkelijk? Waar?",
      translation: "Really? Where?",
      words: [
        { id: "w10", nl: "Werkelijk?", en: ["Really?"] },
        { id: "w11", nl: "Waar?", en: ["Where?"] },
      ],
    },
    {
      id: 7,
      authorIsUser: true,
      isBookmarked: false,
      type: "chatMessage",
      body: "Aan de Universiteit van Amsterdam.",
      translation: "At the university of Darmstadt.",
      words: [
        { id: "w15", nl: "Aan", en: ["At"] },
        { id: "w16", nl: "de Universiteit", en: ["university"] },
        { id: "w17", nl: "van", en: ["of"] },
      ],
    },
    {
      id: 8,
      authorIsUser: false,
      isBookmarked: false,
      type: "chatMessage",
      body: "Werkelijk? Mijn broer studeert daar ook.",
      translation: "Really? My sister studies there too.",
      words: [
        { id: "w1", nl: "Werkelijk?", en: ["Really?"] },
        { id: "w2", nl: "mijn", en: ["my"] },
        { id: "w3", nl: "broer", en: ["brother"] },
        { id: "w4", nl: "studeert", en: ["studies"] },
        { id: "w5", nl: "daar", en: ["there"] },
        { id: "w6", nl: "ook", en: ["too", "also"] },
      ],
    },
    {
      id: 9,
      authorIsUser: false,
      isBookmarked: false,
      type: "chatMessage",
      body: "Moet gaan! Ik ben te laat voor de bus.",
      translation: "Got to go! I am late for the bus.",
      words: [
        { id: "w1", nl: "Ich", en: ["I"] },
        { id: "w2", nl: "moet", en: ["must"] },
        { id: "w3", nl: "gaan", en: ["go", "going", "walking"] },
        { id: "w4", nl: "laat", en: ["late"] },
        { id: "w5", nl: "for", en: ["voor"] },
        { id: "w6", nl: "de Bus", en: ["the Bus"] },
      ],
    },
    {
      id: 10,
      authorIsUser: true,
      isBookmarked: false,
      type: "chatMessage",
      body: "Doei!",
      translation: "Bye!",
      words: [{ id: "w25", nl: "doei", en: ["bye"] }],
    },
    {
      id: 11,
      type: "chatNotification",
      body: "50 new words learned",
    },
  ],
};