export const template = {
    messages: [
      {
        id: 1,
        authorIsUser: false,
        isBookmarked: false,
        datetime: "2022-06-30T13:11:03.000Z",
        type: "chatMessage",
        body: "Hallo! 👋",
        translation: "Hello!",
        words: [{ id: "w1", nl: "hallo", en: ["hello"] }],
      },
      {
        id: 2,
        authorIsUser: false,
        isBookmarked: false,
        datetime: "2022-06-30T13:11:09.000Z",
        type: "chatMessage",
        body: "Aangenaam kennis te maken!",
        translation: "Nice to meet you!",
        words: [
          { id: "w2", nl: "Aangenaam", en: ["nice", "good"] },
          { id: "w3", nl: "te", en: ["you"] },
          { id: "w4", nl: "kennis te maken", en: ["to meet you"] },
        ],
      },
      {
        id: 3,
        authorIsUser: true,
        isBookmarked: false,
        datetime: "2022-06-30T13:12:03.000Z",
        type: "chatMessage",
        body: "Hallo!",
        translation: "Hello!",
        words: [{ id: "w1", nl: "hallo", en: ["hello"] }],
      },
      {
        id: 4,
        authorIsUser: false,
        isBookmarked: false,
        datetime: "2022-06-30T13:12:09.000Z",
        type: "chatMessage",
        body: "Hoe gaat het met je vandaag?",
        translation: "How are you today?",
        words: [
          { id: "w5", nl: "Hoe gaat het", en: ["how are you"] },
          { id: "w6", nl: "vandaag", en: ["today"] },
        ],
      },
      {
        id: 5,
        authorIsUser: true,
        isBookmarked: false,
        datetime: "2022-06-30T13:13:03.000Z",
        type: "chatMessage",
        body: "Goed, dank je wel!",
        translation: "Good, thank you!",
        words: [
          { id: "w8", nl: "Goed", en: ["good", "well", "fine", "nice"] },
          { id: "w9", nl: "dank je wel", en: ["thank you", "thanks"] },
        ],
      },
      {
        id: 6,
        authorIsUser: false,
        isBookmarked: false,
        datetime: "2022-06-30T13:14:09.000Z",
        type: "chatMessage",
        body: "Blij dit te horen.",
        translation: "Happy to hear this.",
        words: [
          { id: "w10", nl: "Blij", en: ["happy", "glad", "pleased"] },
          { id: "w11", nl: "horen", en: ["be", "am"] },
          { id: "w12", nl: "dit", en: ["this"] },
          { id: "w13", nl: "te horen", en: ["to hear", "listen"] },
        ],
      },
      {
        id: 7,
        authorIsUser: false,
        isBookmarked: false,
        datetime: "2022-06-30T13:15:09.000Z",
        type: "chatMessage",
        body: "Mijn naam is Simon.",
        translation: "My name is Simon.",
        words: [
          { id: "w15", nl: "Mijn", en: ["my"] },
          { id: "w16", nl: "naam", en: ["name"] },
          { id: "w17", nl: "is", en: ["is", "be"] },
        ],
      },
      {
        id: 8,
        authorIsUser: false,
        isBookmarked: false,
        datetime: "2022-06-30T13:15:15.000Z",
        type: "chatMessage",
        body: "Ik zal je helpen leren.",
        translation: "I will help you learn.",
        words: [
          { id: "w10", nl: "Ik", en: ["I", "me"] },
          { id: "w18", nl: "Ik zal", en: ["I will"] },
          { id: "w7", nl: "je", en: ["you", "to you"] },
          { id: "w19", nl: "helpen", en: ["help"] },
          { id: "w20", nl: "leren", en: ["learn", "study"] },
        ],
      },
      {
        id: 9,
        authorIsUser: false,
        isBookmarked: false,
        datetime: "2022-06-30T13:15:45.000Z",
        type: "chatMessage",
        body: "Wil je Nederlands leren?",
        translation: "Do you want to learn German?",
        words: [
          { id: "w21", nl: "Wil je", en: ["Do you want", "Would you like"] },
          { id: "w22", nl: "je", en: ["you"] },
          { id: "w23", nl: "Nederlands", en: ["Dutch"] },
          { id: "w24", nl: "leren", en: ["learn", "study"] },
        ],
      },
      {
        id: 10,
        authorIsUser: true,
        isBookmarked: false,
        datetime: "2022-06-30T13:13:03.000Z",
        type: "chatMessage",
        body: "Ja!",
        translation: "Yes!",
        words: [{ id: "w25", nl: "Ja", en: ["Yes"] }],
      },
      {
        id: 11,
        type: "chatNotification",
        body: "25 new words learned",
      },
    ],
  };